server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: circuit-breaker
          uri: https://github.com/samuelboada21/microservicios-spring
          search-paths: config-data
  application:
    name: config-service